name: Lint and test
on: [push]

jobs:
    test-lint:
        env:
            WP_VERSION: 'latest'
            WP_MULTISITE: 0
            WP_CORE_DIR: '/tmp/wordpress'
            COMPOSER_DEV: 1

        runs-on: ubuntu-latest
        strategy:
            matrix:
                # php: ['7.0', '7.1', '7.2', '7.3']
                php: ['7.3']
                # wordpress: ['5.3', '5.4', '5.5']
                wordpress: [5.5]
                # woocommerce: ['4.7.1', '4.8.0', '4.9.0', '4.9.1']
                woocommerce: ['4.9.1']
                phpunit: ['latest']
                # include:
                #     - php: '7.0'
                #       phpunit: 6
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@2.9.0
              with:
                  php-version: ${{matrix.php}}
                  tools: phpunit
            - name: Install PHP dependencies
              run: |
                  composer self-update 2.0.6
                  composer i
            - name: Setup Node.js
              uses: actions/setup-node@v2-beta
              with:
                  node-version: '14'
            # - name: Install supporting tools
            #   run: |
            #     sudo apt update
            #     sudo apt-get install subversion -y
            #     sudo apt-get install mysql-client -y
            - name: Set up the tests
              env:
                  WP_VERSION: ${{matrix.wordpress}}
                  WC_VERSION: ${{matrix.woocommerce}}
                  PHP_UNIT: ${{matrix.phpunit}}
              run: |
                  sudo /etc/init.d/mysql start
                  bash bin/gh-install-wp-tests.sh wc_admin_test root 'root' localhost
                  bash bin/gh.sh
                  node --version
                  npm --version
                  timedatectl
            - name: Lint the JS
              run: bin/js_lint_test.sh
              shell: bash
            - name: Lint the PHP
              run: bin/phpcs.sh
              shell: bash
            - name: Run the PHP unit tests
              run: bin/phpunit.sh
              shell: bash
